// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package session

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson42239ddeDecodeGithubComMstojcevichLambdaNgGoUserSession(in *jlexer.Lexer, out *LambdaSession) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "api_key":
			out.APIKey = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson42239ddeEncodeGithubComMstojcevichLambdaNgGoUserSession(out *jwriter.Writer, in LambdaSession) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"api_key\":"
		out.RawString(prefix[1:])
		out.String(string(in.APIKey))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LambdaSession) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson42239ddeEncodeGithubComMstojcevichLambdaNgGoUserSession(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LambdaSession) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson42239ddeEncodeGithubComMstojcevichLambdaNgGoUserSession(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LambdaSession) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson42239ddeDecodeGithubComMstojcevichLambdaNgGoUserSession(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LambdaSession) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson42239ddeDecodeGithubComMstojcevichLambdaNgGoUserSession(l, v)
}
